apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: elk-certificate-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /vagrant/web/Certifications/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
